export const initialState = {
    id: "",
    firstName: "",
    companyName: "",
    address: "",
    apartment: "",
    city: "",
    phoneNumber: "",
    email: "",
    transactionId: "",
    refId: "",
    userId: "",
    items: [],
    paymentStatus: "",
    paymentMode: "",
    subtotal: 0,
    deliveryFee: 0,
    total: 0,
    orderStatus: "",
    createdAt: "",
    updatedAt: "",
  };