export const initialState = {
  id: "",
  name: "",
  brand: "",
  description: "",
  category: "",
  subCategory: "",
  photo: [],
  price: 0,
  discountedPrice: null,
  rating: [],
  reviews: [],
  inStock: 0,
  likes: [],
  views: [],
  color: "",
  allColors: [],
  size: "",
  allSizes: [],
  isNewArrival: false,
  isFlashSales: false,
  isExplore: false,
  isBestSelling: false,
  otherSizeInfo: {
    XS: { inStock: 0, price: 0, discountedPrice: 0 },
    S: { inStock: 0, price: 0, discountedPrice: 0 },
    M: { inStock: 0, price: 0, discountedPrice: 0 },
    L: { inStock: 0, price: 0, discountedPrice: 0 },
    XL: { inStock: 0, price: 0, discountedPrice: 0 },
  },
  createdAt: "",
  upDatedAt: "",
};
