export const initialState = {
  id: "",
  firstName: "",
  lastName: "",
  email: "",
  emailVerified: false,
  phoneNumber: "",
  photoUrl: "",
  address: "",
  companyName: "",
  apartment: "",
  city: "",
  isAdmin: false,
  isOwner: false,
  isSignedIn: false,
  lastLoginAt: "",
  lastLogoutAt: "",
  createdAt: "",
  updatedAt: "",
};
