import flashsaleGamePad from "../assets/flashsaleGamePad.png";
import flashsaleKeyboard from "../assets/flashsaleKeyboard.png";
import flashsaleTv from "../assets/flashsaleTv.png";
import flashsaleChair from "../assets/flashsaleChair.png";
import homeCoatImg from "../assets/homeCoatImg.png";
import homeBagImg from "../assets/homeBagImg.png";
import homeCoolerImg from "../assets/homeCoolerImg.png";
import homeShelfImg from "../assets/homeShelfImg.png";
import homeDogFood from "../assets/homeDogFood.png";
import homeCamera from "../assets/homeCamera.png";
import homeLaptop from "../assets/homeLaptop.png";
import homeKidsCar from "../assets/homeKidsCar.png";
import homeSoccerBoot from "../assets/homeSoccerBoot.png";
import homeUsbGamePad from "../assets/homeUsbGamePad.png";
import homeJacket from "../assets/homeJacket.png";
import { ProductType } from "../states/redux/reducerTypes";

export const products: ProductType[] = [
  {
    id: "1",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "gaming",
    photo: [
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
    ],
    price: "160",
    discountedPrice: "120",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "5"],
    quantity: 6,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0000ff", "#008000"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "101",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "gaming",
    photo: [
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
    ],
    price: "160",
    discountedPrice: "120",
    reviews: ["nice product", "i love it"],
    rating: ["4.5", "5", "4.3", "2.4"],
    quantity: 6,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#0000ff",
    allColors: ["#ff0000", "#0000ff", "#008000"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "101a",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "gaming",
    photo: [
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
    ],
    price: "160",
    discountedPrice: "120",
    reviews: ["nice product", "i love it"],
    rating: ["4.5", "1", "4.3", "4.4"],
    quantity: 6,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#008000",
    allColors: ["#ff0000", "#0000ff", "#008000"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [flashsaleKeyboard, flashsaleKeyboard, flashsaleKeyboard],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["4.1", "2", "5", "3.5"],
    quantity: 5,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#008000",
    allColors: ["#ff0000", "#008000"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "102",
    name: "AK-900 Wired Keyboard",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [flashsaleKeyboard, flashsaleKeyboard, flashsaleKeyboard],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["4", "2.6", "5", "3.5"],
    quantity: 5,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#008000"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "3",
    name: "IPS LCD Gaming Monitor",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [flashsaleTv, flashsaleTv, flashsaleTv, flashsaleTv],
    price: "400",
    discountedPrice: "370",
    reviews: ["nice product", "i love it"],
    rating: ["4", "1", "5", "3.5"],
    quantity: 7,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "4",
    name: "S-Series Comfort Chair",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-office",
    subCategory: "furniture",
    photo: [flashsaleChair, flashsaleChair, flashsaleChair, flashsaleChair],
    price: "400",
    discountedPrice: "375",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "3.5"],
    quantity: 6,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "5",
    name: "The north coat",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "men-and-women",
    photo: [homeCoatImg, homeCoatImg, homeCoatImg],
    price: "360",
    discountedPrice: "260",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "3.5"],
    quantity: 17,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "6",
    name: "Gucci duffle bag",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing-accessories",
    subCategory: "Bags",
    photo: [homeBagImg, homeBagImg, homeBagImg, homeBagImg, homeBagImg],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["4", "4.8", "4.7", "3.5"],
    quantity: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "7",
    name: "RGB liquid CPU Cooler",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
    ],
    price: "170",
    discountedPrice: "160",
    reviews: ["nice product", "i love it"],
    rating: ["4", "4.8", "4.7", "3"],
    quantity: 8,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "8",
    name: "Small BookShelf",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-office ",
    subCategory: "furniture ",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3"],
    quantity: 1,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "9",
    name: "Breed Dry Dog Food",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "pet-supplies",
    subCategory: "pet-food",
    photo: [homeDogFood, homeDogFood, homeDogFood],
    price: "100",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3.5"],
    quantity: 45,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "10",
    name: "CANON EOS DSLR Camera",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "cameras",
    photo: [homeCamera, homeCamera, homeCamera, homeCamera],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3"],
    quantity: 15,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "11",
    name: "ASUS FHD Gaming Laptop",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "laptops",
    photo: [homeLaptop, homeLaptop, homeLaptop, homeLaptop],
    price: "700",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["4", "2.8", "4.7", "3"],
    quantity: 9,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "12",
    name: "Kids Electric Car",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "toys",
    subCategory: "outdoor-toys",
    photo: [homeKidsCar, homeKidsCar, homeKidsCar],
    price: "960",
    discountedPrice: "800",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 34,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "13",
    name: "Jr. Zoom Soccer Cleats",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "sports",
    subCategory: "football-kits",
    photo: [homeSoccerBoot, homeSoccerBoot, homeSoccerBoot],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 16,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "14",
    name: "GP11 Shooter USB Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "gaming",
    photo: [homeUsbGamePad, homeUsbGamePad, homeUsbGamePad, homeUsbGamePad],
    price: "660",
    discountedPrice: "450",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 35,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "15",
    name: "Quilted Satin Jacket",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "men-and-women",
    photo: [homeJacket, homeJacket, homeJacket],
    price: "660",
    discountedPrice: "500",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 22,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "16",
    name: "Female Jacket1",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "women",
    photo: [homeJacket, homeJacket, homeJacket],
    price: "660",
    discountedPrice: "500",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 8,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "17",
    name: "Male Jacket1",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "men",
    photo: [homeJacket, homeJacket, homeJacket],
    price: "660",
    discountedPrice: "500",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "18",
    name: "Female Jacket2",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "women",
    photo: [homeJacket, homeJacket, homeJacket],
    price: "660",
    discountedPrice: "500",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 21,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "19",
    name: "Male Jacket2",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing",
    subCategory: "men",
    photo: [homeJacket, homeJacket, homeJacket],
    price: "660",
    discountedPrice: "500",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 8,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "20",
    name: "Female bag",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "women",
    subCategory: "bags",
    photo: [homeBagImg, homeBagImg, homeBagImg, homeBagImg],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    quantity: 6,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "21",
    name: "Male bag",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "men",
    subCategory: "bags",
    photo: [homeBagImg, homeBagImg, homeBagImg],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 3,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "22",
    name: "Home BookShelf1",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 2,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "23",
    name: "Home BookShelf2",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 8,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "24",
    name: "Home BookShelf3",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 12,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "25",
    name: "Home BookShelf4",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 25,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "26",
    name: "Home BookShelf5",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    quantity: 16,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "27",
    name: "Panadol",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "medicine",
    subCategory: "pain-relief",
    photo: [homeDogFood, homeDogFood, homeDogFood],
    price: "100",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "4.7", "2.1", "3"],
    quantity: 36,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "28",
    name: "Paracetamol",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "medicine",
    subCategory: "pain-relief",
    photo: [homeDogFood, homeDogFood, homeDogFood],
    price: "100",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "3"],
    quantity: 32,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "29",
    name: "Boots",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "sports",
    subCategory: "football-kits",
    photo: [homeSoccerBoot, homeSoccerBoot, homeSoccerBoot],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["3", "3"],
    quantity: 21,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "30",
    name: "Cleat",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "sports",
    subCategory: "football-kits",
    photo: [homeSoccerBoot, homeSoccerBoot, homeSoccerBoot],
    price: "1160",
    discountedPrice: "960",
    reviews: ["nice product", "i love it"],
    rating: ["3", "3"],
    quantity: 14,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "31",
    name: "Kids Electric Car",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "toys",
    subCategory: "outdoor-toys",
    photo: [homeKidsCar, homeKidsCar, homeKidsCar, homeKidsCar],
    price: "960",
    discountedPrice: "800",
    reviews: ["nice product", "i love it"],
    rating: ["3", "3"],
    quantity: 23,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "32",
    name: "Groceries1",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "groceries",
    subCategory: "pet-food",
    photo: [homeDogFood, homeDogFood, homeDogFood, homeDogFood],
    price: "100",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3", "3"],
    quantity: 7,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "33",
    name: "Groceries2",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "groceries",
    subCategory: "pet-food",
    photo: [homeDogFood, homeDogFood, homeDogFood],
    price: "100",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["3.2"],
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    quantity: 7,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "34",
    name: "Barbell",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "health",
    subCategory: "fitness-equipment",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["1.2"],
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    quantity: 29,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "35",
    name: "Make Up",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "beauty",
    subCategory: "make-up",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg],
    price: "360",
    discountedPrice: "",
    reviews: ["nice product", "i love it"],
    rating: ["0"],
    allColors: ["#A0BCE0", "#E07575"],
    size: ["XS", "S","M","L","XL"],
    quantity: 46,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
];
