import flashsaleGamePad from "../assets/flashsaleGamePad.png";
import flashsaleKeyboard from "../assets/flashsaleKeyboard.png";
import flashsaleTv from "../assets/flashsaleTv.png";
import flashsaleChair from "../assets/flashsaleChair.png";
import homeCoatImg from "../assets/homeCoatImg.png";
import homeBagImg from "../assets/homeBagImg.png";
import homeCoolerImg from "../assets/homeCoolerImg.png";
import homeShelfImg from "../assets/homeShelfImg.png";
import homeDogFood from "../assets/homeDogFood.png";
import homeCamera from "../assets/homeCamera.png";
import homeLaptop from "../assets/homeLaptop.png";
import homeKidsCar from "../assets/homeKidsCar.png";
import homeSoccerBoot from "../assets/homeSoccerBoot.png";
import homeUsbGamePad from "../assets/homeUsbGamePad.png";
import homeJacket from "../assets/homeJacket.png";
import newArrivalPs5 from "../assets/newArrivalPs5.png";
import newArrivalPerfume from "../assets/newArrivalPerfume.png";
import newArrivalSpeaker from "../assets/newArrivalSpeaker.png";
import { ProductType } from "../states/redux/reducerTypes";

export const products: ProductType[] = [
  {
    id: "5",
    name: "The north coat",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "women's-fashion",
    subCategory: "phones",
    photo: [homeCoatImg, homeCoatImg, homeCoatImg],
    price: 360,
    discountedPrice: 260,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "15",
    name: "Quilted Satin Jacket",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "men's-fashion",
    subCategory: "computers",
    photo: [homeJacket, homeJacket, homeJacket],
    price: 660,
    discountedPrice: 500,
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "1",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "smart-watch",
    photo: [
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
      flashsaleGamePad,
    ],
    price: 160,
    discountedPrice: 120,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0000ff", "#008000"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "10",
    name: "CANON EOS DSLR Camera",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "cameras",
    photo: [homeCamera, homeCamera, homeCamera, homeCamera],
    price: 360,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "8",
    name: "Small BookShelf",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-lifestyle",
    subCategory: "headphones",
    photo: [homeShelfImg, homeShelfImg, homeShelfImg, homeShelfImg],
    price: 360,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "14",
    name: "GP11 Shooter USB Gamepad",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "medicine",
    subCategory: "gaming",
    photo: [homeUsbGamePad, homeUsbGamePad, homeUsbGamePad, homeUsbGamePad],
    price: 660,
    discountedPrice: 450,
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#A0BCE0", "#E07575"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "13",
    name: "Jr. Zoom Soccer Cleats",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "sports-&-outdoors",
    subCategory: "football-kits",
    photo: [homeSoccerBoot, homeSoccerBoot, homeSoccerBoot],
    price: 1160,
    discountedPrice: 960,
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "12",
    name: "Kids Electric Car",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "baby's-&-toys",
    subCategory: "outdoor-toys",
    photo: [homeKidsCar, homeKidsCar, homeKidsCar],
    price: 960,
    discountedPrice: 800,
    reviews: ["nice product", "i love it"],
    rating: ["5", "1", "3.6", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "9",
    name: "Breed Dry Dog Food",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "groceries-&-pets",
    subCategory: "pet-food",
    photo: [homeDogFood, homeDogFood, homeDogFood],
    price: 100,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.7", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "38",
    name: "Perfume",
    brand: "",
    description: "GUCCI INTENSE OUD EDP",
    category: "health-&-beauty",
    subCategory: "Fragrance",
    photo: [newArrivalPerfume, newArrivalPerfume, newArrivalPerfume],
    price: 1000,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["0"],
    allColors: ["#000000", "#E07575"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#000000",
    isNewArrival: true,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },

  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [flashsaleKeyboard, flashsaleKeyboard, flashsaleKeyboard],
    price: 1160,
    discountedPrice: 960,
    reviews: ["nice product", "i love it"],
    rating: ["4.1", "2", "5", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#008000",
    allColors: ["#ff0000", "#008000"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },

  {
    id: "3",
    name: "IPS LCD Gaming Monitor",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [flashsaleTv, flashsaleTv, flashsaleTv, flashsaleTv],
    price: 400,
    discountedPrice: 370,
    reviews: ["nice product", "i love it"],
    rating: ["4", "1", "5", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "4",
    name: "S-Series Comfort Chair",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-office",
    subCategory: "furniture",
    photo: [flashsaleChair, flashsaleChair, flashsaleChair, flashsaleChair],
    price: 400,
    discountedPrice: 375,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "4a",
    name: "S-Series Comfort Chair",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "home-and-office",
    subCategory: "furniture",
    photo: [flashsaleChair, flashsaleChair, flashsaleChair, flashsaleChair],
    price: 400,
    discountedPrice: 375,
    reviews: ["nice product", "i love it"],
    rating: ["4", "5", "4.3", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: [],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },

  {
    id: "6",
    name: "Gucci duffle bag",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "clothing-accessories",
    subCategory: "Bags",
    photo: [homeBagImg, homeBagImg, homeBagImg, homeBagImg, homeBagImg],
    price: 1160,
    discountedPrice: 960,
    reviews: ["nice product", "i love it"],
    rating: ["4", "4.8", "4.7", "3.5"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "7",
    name: "RGB liquid CPU Cooler",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: [
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
      homeCoolerImg,
    ],
    price: 170,
    discountedPrice: 160,
    reviews: ["nice product", "i love it"],
    rating: ["4", "4.8", "4.7", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },

  {
    id: "11",
    name: "ASUS FHD Gaming Laptop",
    brand: "",
    description: "A very good item with versatility, good for dynamic usage",
    category: "electronics",
    subCategory: "laptops",
    photo: [homeLaptop, homeLaptop, homeLaptop, homeLaptop],
    price: 700,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["4", "2.8", "4.7", "3"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#ff0000",
    allColors: ["#ff0000", "#0a0520"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },

  {
    id: "36",
    name: "PlayStation 5",
    brand: "",
    description: "Black and White version of the PS5 coming out on sale.",
    category: "electronics",
    subCategory: "gaming",
    photo: [newArrivalPs5, newArrivalPs5, newArrivalPs5],
    price: 1000,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["0"],
    allColors: ["#000000", "#E07575"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#000000",
    isNewArrival: true,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
  {
    id: "37",
    name: "Speakers",
    brand: "",
    description: "Amazon wireless speakers",
    category: "electronics",
    subCategory: "sound-system",
    photo: [newArrivalSpeaker, newArrivalSpeaker, newArrivalSpeaker],
    price: 1000,
    discountedPrice: null,
    reviews: ["nice product", "i love it"],
    rating: ["0"],
    allColors: ["#000000", "#E07575"],
    size: "M",
    allSizes: ["XS", "S", "M", "L", "XL"],
    inStock: 4,
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: "#000000",
    isNewArrival: true,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    otherSizeInfo: {
      XS: { inStock: 1, price: 100, discountedPrice: 70 },
      S: { inStock: 2, price: 100, discountedPrice: 80 },
      M: { inStock: 4, price: 100, discountedPrice: 90 },
      L: { inStock: 2, price: 100, discountedPrice: 80 },
      XL: { inStock: 1, price: 100, discountedPrice: 70 },
    },
    createdAt: "",
    upDatedAt: "",
  },
];
