import flashsaleGamePad from "../assets/flashsaleGamePad.png";
import flashsaleKeyboard from "../assets/flashsaleKeyboard.png";
import flashsaleTv from "../assets/flashsaleTv.png";
import flashsaleChair from "../assets/flashsaleChair.png";
import homeCoatImg from "../assets/homeCoatImg.png";
import homeBagImg from "../assets/homeBagImg.png";
import homeCoolerImg from "../assets/homeCoolerImg.png";
import homeShelfImg from "../assets/homeShelfImg.png";
import homeDogFood from "../assets/homeDogFood.png";
import homeCamera from "../assets/homeCamera.png";
import homeLaptop from "../assets/homeLaptop.png";
import homeKidsCar from "../assets/homeKidsCar.png";
import homeSoccerBoot from "../assets/homeSoccerBoot.png";
import homeUsbGamePad from "../assets/homeUsbGamePad.png";
import homeJacket from "../assets/homeJacket.png";
import { ProductType } from "../states/redux/reducerTypes";

export const products: ProductType[] = [
  {
    id: "1",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    category: "electronics",
    subCategory: "gaming",
    photo: flashsaleGamePad,
    price: "160",
    discountedPrice: "120",
    rating: 4.25,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "101",
    name: "HAVIT HV-G92 Gamepad",
    brand: "",
    category: "electronics",
    subCategory: "gaming",
    photo: flashsaleGamePad,
    price: "160",
    discountedPrice: "120",
    rating: 4.25,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["X", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    brand: "",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: flashsaleKeyboard,
    price: "1160",
    discountedPrice: "960",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "5",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["X", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "102",
    name: "AK-900 Wired Keyboard",
    brand: "",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: flashsaleKeyboard,
    price: "1160",
    discountedPrice: "960",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "5",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["X", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "3",
    name: "IPS LCD Gaming Monitor",
    brand: "",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: flashsaleTv,
    price: "400",
    discountedPrice: "370",
    rating: 4,
    reviews: ["Nice one", "great product"],
    quantity: "7",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["X", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "4",
    name: "S-Series Comfort Chair",
    brand: "",
    category: "home-and-office",
    subCategory: "furniture",
    photo: flashsaleChair,
    price: "400",
    discountedPrice: "375",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: false,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "5",
    name: "The north coat",
    brand: "",
    category: "clothing",
    subCategory: "men-and-women",
    photo: homeCoatImg,
    price: "360",
    discountedPrice: "260",
    rating: 3,
    reviews: ["Nice one", "great product"],
    quantity: "17",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "6",
    name: "Gucci duffle bag",
    brand: "",
    category: "clothing-accessories",
    subCategory: "Bags",
    photo: homeBagImg,
    price: "1160",
    discountedPrice: "960",
    rating: 1,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "7",
    name: "RGB liquid CPU Cooler",
    brand: "",
    category: "electronics",
    subCategory: "computer-accessories",
    photo: homeCoolerImg,
    price: "170",
    discountedPrice: "160",
    rating: 4,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "8",
    name: "Small BookShelf",
    brand: "",
    category: "home-and-office ",
    subCategory: "furniture ",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "9",
    name: "Breed Dry Dog Food",
    brand: "",
    category: "pet-supplies",
    subCategory: "pet-food",
    photo: homeDogFood,
    price: "100",
    discountedPrice: "",
    rating: 3,
    reviews: ["Nice one", "great product"],
    quantity: "60",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "10",
    name: "CANON EOS DSLR Camera",
    brand: "",
    category: "electronics",
    subCategory: "cameras",
    photo: homeCamera,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "15",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "11",
    name: "ASUS FHD Gaming Laptop",
    brand: "",
    category: "electronics",
    subCategory: "laptops",
    photo: homeLaptop,
    price: "700",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "9",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "12",
    name: "Kids Electric Car",
    brand: "",
    category: "toys",
    subCategory: "outdoor-toys",
    photo: homeKidsCar,
    price: "960",
    discountedPrice: "800",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "18",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "13",
    name: "Jr. Zoom Soccer Cleats",
    brand: "",
    category: "sports",
    subCategory: "football-kits",
    photo: homeSoccerBoot,
    price: "1160",
    discountedPrice: "960",
    rating: 4.3,
    reviews: ["Nice one", "great product"],
    quantity: "44",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "14",
    name: "GP11 Shooter USB Gamepad",
    brand: "",
    category: "electronics",
    subCategory: "gaming",
    photo: homeUsbGamePad,
    price: "660",
    discountedPrice: "450",
    rating: 3.8,
    reviews: ["Nice one", "great product"],
    quantity: "10",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "15",
    name: "Quilted Satin Jacket",
    brand: "",
    category: "clothing",
    subCategory: "men-and-women",
    photo: homeJacket,
    price: "660",
    discountedPrice: "500",
    rating: 4.5,
    reviews: ["Nice one", "great product"],
    quantity: "71",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "16",
    name: "Female Jacket1",
    brand: "",
    category: "clothing",
    subCategory: "women",
    photo: homeJacket,
    price: "660",
    discountedPrice: "500",
    rating: 4.5,
    reviews: ["Nice one", "great product"],
    quantity: "71",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "17",
    name: "Male Jacket1",
    brand: "",
    category: "clothing",
    subCategory: "men",
    photo: homeJacket,
    price: "660",
    discountedPrice: "500",
    rating: 4.5,
    reviews: ["Nice one", "great product"],
    quantity: "71",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "18",
    name: "Female Jacket2",
    brand: "",
    category: "clothing",
    subCategory: "women",
    photo: homeJacket,
    price: "660",
    discountedPrice: "500",
    rating: 4.5,
    reviews: ["Nice one", "great product"],
    quantity: "71",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "19",
    name: "Male Jacket2",
    brand: "",
    category: "clothing",
    subCategory: "men",
    photo: homeJacket,
    price: "660",
    discountedPrice: "500",
    rating: 4.5,
    reviews: ["Nice one", "great product"],
    quantity: "71",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "20",
    name: "Female bag",
    brand: "",
    category: "women",
    subCategory: "bags",
    photo: homeBagImg,
    price: "1160",
    discountedPrice: "960",
    rating: 1,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "21",
    name: "Male bag",
    brand: "",
    category: "men",
    subCategory: "bags",
    photo: homeBagImg,
    price: "1160",
    discountedPrice: "960",
    rating: 1,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: [],
    size: [],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: false,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "22",
    name: "Home BookShelf1",
    brand: "",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "23",
    name: "Home BookShelf2",
    brand: "",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "24",
    name: "Home BookShelf3",
    brand: "",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "25",
    name: "Home BookShelf4",
    brand: "",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "26",
    name: "Home BookShelf5",
    brand: "",
    category: "home-and-lifeStyle",
    subCategory: "furniture",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    color: ["red", "green"],
    size: ["x", "xl"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "27",
    name: "Panadol",
    brand: "",
    category: "medicine",
    subCategory: "pain-relief",
    photo: homeDogFood,
    price: "100",
    discountedPrice: "",
    rating: 3,
    reviews: ["Nice one", "great product"],
    quantity: "60",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "28",
    name: "Paracetamol",
    brand: "",
    category: "medicine",
    subCategory: "pain-relief",
    photo: homeDogFood,
    price: "100",
    discountedPrice: "",
    rating: 3,
    reviews: ["Nice one", "great product"],
    quantity: "60",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "29",
    name: "Boots",
    brand: "",
    category: "sports",
    subCategory: "football-kits",
    photo: homeSoccerBoot,
    price: "1160",
    discountedPrice: "960",
    rating: 4.3,
    reviews: ["Nice one", "great product"],
    quantity: "44",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "30",
    name: "Cleat",
    brand: "",
    category: "sports",
    subCategory: "football-kits",
    photo: homeSoccerBoot,
    price: "1160",
    discountedPrice: "960",
    rating: 4.3,
    reviews: ["Nice one", "great product"],
    quantity: "44",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "31",
    name: "Kids Electric Car",
    brand: "",
    category: "toys",
    subCategory: "outdoor-toys",
    photo: homeKidsCar,
    price: "960",
    discountedPrice: "800",
    rating: 5,
    reviews: ["Nice one", "great product"],
    quantity: "18",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "32",
    name: "Groceries1",
    brand: "",
    category: "groceries",
    subCategory: "pet-food",
    photo: homeDogFood,
    price: "100",
    discountedPrice: "",
    rating: 3,
    reviews: ["Nice one", "great product"],
    quantity: "60",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    color: ["red", "green"],
    size: ["x", "xl"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "33",
    name: "Groceries2",
    brand: "",
    category: "groceries",
    subCategory: "pet-food",
    photo: homeDogFood,
    price: "100",
    discountedPrice: "",
    rating: 3,
    reviews: ["Nice one", "great product"],
    color: ["red", "green"],
    size: ["x", "xl"],
    quantity: "60",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    isNewArrival: false,
    isFlashSales: false,
    isExplore: true,
    isBestSelling: false,
    timeStamp: "",
  },
  {
    id: "33",
    name: "Barbell",
    brand: "",
    category: "health",
    subCategory: "fitness-equipment",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    color: ["red", "green"],
    size: ["x", "xl"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  {
    id: "34",
    name: "Make Up",
    brand: "",
    category: "beauty",
    subCategory: "make-up",
    photo: homeShelfImg,
    price: "360",
    discountedPrice: "",
    rating: 5,
    reviews: ["Nice one", "great product"],
    color: ["red", "green"],
    size: ["x", "xl"],
    quantity: "6",
    likes: ["a", " b", "c"],
    views: ["a", "b", "c", "d"],
    isNewArrival: false,
    isFlashSales: true,
    isExplore: true,
    isBestSelling: true,
    timeStamp: "",
  },
  
];
